---
- name: install and start services
  hosts: ansible1
  vars:
    services:
    - vsftpd
    - httpd
    - smb
  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: latest
    loop: "{{ services }}"
  - name: start the services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: "{{ services }}"

